import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Admin kullanıcısı oluştur
  const hashedPassword = await bcrypt.hash('Admin123!', 10)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@lioradg.com.tr' },
    update: {},
    create: {
      email: 'admin@lioradg.com.tr',
      name: 'Liora Admin',
      password: hashedPassword,
      role: 'ADMIN',
    },
  })
  console.log('✅ Admin kullanıcısı oluşturuldu:', admin.email)

  // Kategorileri oluştur
  const categories = [
    {
      name: 'Parfümler',
      slug: 'parfumler',
      description: 'Kalıcı ve büyüleyici parfüm koleksiyonumuz',
      icon: '💐',
      image: '/images/parfumler/1.jpg',
      order: 1,
    },
    {
      name: 'Tonikler',
      slug: 'tonikler',
      description: 'Cildinizi canlandıran doğal tonikler',
      icon: '💧',
      image: '/images/tonikler/1.jpg',
      order: 2,
    },
    {
      name: 'Şampuan & Saç Bakım',
      slug: 'sampuan-sac-bakim',
      description: 'Saçlarınız için doğal bakım ürünleri',
      icon: '💆',
      image: '/images/sampuan-sacbakim/1.jpg',
      order: 3,
    },
    {
      name: 'Krem Bakım',
      slug: 'krem-bakim',
      description: 'Cildinizi besleyen profesyonel bakım kremleri',
      icon: '🧴',
      image: '/images/krembakim/1.jpg',
      order: 4,
    },
    {
      name: 'Bitkisel Yağlar',
      slug: 'bitkisel-yaglar',
      description: 'Difüzör için doğal esans yağları',
      icon: '🌿',
      image: '/images/bitkiselyaglar/1.jpg',
      order: 5,
    },
    {
      name: 'Oda ve Tekstil Kokuları',
      slug: 'oda-tekstil-kokulari',
      description: 'Evinizi ferahlatan oda kokuları',
      icon: '🕯️',
      image: '/images/odavetekstil/1.jpg',
      order: 6,
    },
  ]

  const createdCategories: any = {}
  for (const cat of categories) {
    const category = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    })
    createdCategories[cat.slug] = category
    console.log(`✅ Kategori oluşturuldu: ${category.name}`)
  }

  // Ürünleri oluştur
  const products = [
    // Parfümler
    {
      name: 'Erkek Parfüm - 100 ml',
      slug: 'erkek-parfum-100ml',
      description: 'Erkekler için özel olarak tasarlanmış, kalıcı ve etkileyici parfüm. Odunsu ve baharatlı notalar.',
      content: 'Üst notalar: Bergamot, Limon\nOrta notalar: Lavanta, Karanfil\nAlt notalar: Sandal ağacı, Amber',
      usage: 'Parfümü boyun, bilek ve kulak arkası gibi nabız noktalarına sıkın. Ovmayın, kurumaya bırakın.',
      price: 299.90,
      salePrice: 249.90,
      sku: 'PRF-ERK-001',
      stock: 50,
      images: '/images/parfumler/1.jpg',
      featured: true,
      categoryId: createdCategories['parfumler'].id,
    },
    {
      name: 'Kadın Parfüm - 100 ml',
      slug: 'kadin-parfum-100ml',
      description: 'Zarif ve feminen bir koku. Çiçeksi ve meyvemsi notalar kadınlar için özel olarak hazırlandı.',
      content: 'Üst notalar: Gül, Yasemin\nOrta notalar: Iris, Turunç çiçeği\nAlt notalar: Vanilya, Misk',
      usage: 'Parfümü boyun, bilek ve kulak arkası gibi nabız noktalarına sıkın. Ovmayın, kurumaya bırakın.',
      price: 299.90,
      salePrice: 249.90,
      sku: 'PRF-KDN-001',
      stock: 50,
      images: '/images/parfumler/2.jpg',
      featured: true,
      categoryId: createdCategories['parfumler'].id,
    },
    // Tonikler
    {
      name: 'Saf Biberiye Suyu Tonik - 100 ml',
      slug: 'saf-biberiye-suyu-tonik-100ml',
      description: 'Cildi canlandıran ve ferahlatan doğal biberiye suyu. Yağlı ve karışık ciltler için ideal.',
      content: '%100 doğal biberiye suyu. Paraben, alkol ve kimyasal katkı içermez.',
      usage: 'Temizlenmiş yüze pamuk yardımıyla uygulayın. Günde 2 kez kullanılabilir.',
      price: 149.90,
      sku: 'TNK-BBR-001',
      stock: 100,
      images: '/images/tonikler/1.jpg',
      featured: true,
      categoryId: createdCategories['tonikler'].id,
    },
    {
      name: 'Saf Ölmez Çiçek Suyu Tonik - 100 ml',
      slug: 'saf-olmez-cicek-suyu-tonik-100ml',
      description: 'Anti-aging özellikleriyle bilinen ölmez çiçek suyu. Cildi sıkılaştırır ve gençleştirir.',
      content: '%100 doğal ölmez çiçek (helichrysum) suyu. Tüm cilt tipleri için uygundur.',
      usage: 'Temizlenmiş yüze pamuk yardımıyla uygulayın. Sabah ve akşam kullanılabilir.',
      price: 169.90,
      sku: 'TNK-OLM-001',
      stock: 80,
      images: '/images/tonikler/2.jpg',
      categoryId: createdCategories['tonikler'].id,
    },
    {
      name: 'Saf Gül Mayası Tonik - 100 ml',
      slug: 'saf-gul-mayasi-tonik-100ml',
      description: 'Cildi nemlendiren ve yumuşatan gül mayası tonik. Hassas ciltler için mükemmel.',
      content: '%100 doğal gül mayası. Cildi yatıştırır, kızarıklıkları azaltır.',
      usage: 'Temizlenmiş cilde pamuk ile uygulayın. Günde 2-3 kez kullanılabilir.',
      price: 159.90,
      salePrice: 139.90,
      sku: 'TNK-GUL-001',
      stock: 90,
      images: '/images/tonikler/3.jpg',
      featured: true,
      categoryId: createdCategories['tonikler'].id,
    },
    {
      name: 'Japon Kiraz Çiçeği Saç Sirkesi - 200 ml',
      slug: 'japon-kiraz-cicegi-sac-sirkesi-200ml',
      description: 'Saçları parlatıp yumuşatan doğal saç sirkesi. pH dengesini sağlar.',
      content: 'Elma sirkesi bazlı, Japon kiraz çiçeği özlü doğal formül.',
      usage: 'Şampuan sonrası saça uygulayın, 2-3 dakika bekleyin ve durulayın.',
      price: 129.90,
      sku: 'TNK-KRZ-001',
      stock: 60,
      images: '/images/tonikler/4.jpg',
      categoryId: createdCategories['tonikler'].id,
    },
    {
      name: 'Makyaj Temizleme Suyu',
      slug: 'makyaj-temizleme-suyu',
      description: 'Etkili ve nazik makyaj temizleme suyu. Tüm makyaj ürünlerini kolayca çıkarır.',
      content: 'Micellar teknoloji ile geliştirilmiş, yağsız formül. Göz makyajı için de uygundur.',
      usage: 'Pamuk yardımıyla yüze uygulayın ve makyajı temizleyin. Durulamaya gerek yoktur.',
      price: 119.90,
      sku: 'TNK-MKJ-001',
      stock: 70,
      images: '/images/tonikler/5.jpg',
      categoryId: createdCategories['tonikler'].id,
    },
    // Şampuan & Saç Bakım
    {
      name: 'Biberiye Argan Yasemin Şampuanı - 400 ml',
      slug: 'biberiye-argan-yasemin-sampuani-400ml',
      description: 'Saç dökülmesini azaltan, saçları besleyen doğal şampuan.',
      content: 'Biberiye, argan yağı ve yasemin özü içerir. SLS/SLES içermez.',
      usage: 'Islak saça uygulayın, masaj yapın ve durulayın. Günlük kullanıma uygundur.',
      price: 189.90,
      salePrice: 169.90,
      sku: 'SMP-BBR-001',
      stock: 75,
      images: '/images/sampuan-sacbakim/1.jpg',
      featured: true,
      categoryId: createdCategories['sampuan-sac-bakim'].id,
    },
    {
      name: 'Melisa Buğday At Kuyruğu Saç Kremi - 400 ml',
      slug: 'melisa-bugday-at-kuyrugu-sac-kremi-400ml',
      description: 'Saçları yumuşatıp güçlendiren besleyici saç kremi.',
      content: 'Melisa, buğday proteini ve at kuyruğu özü ile zenginleştirilmiş.',
      usage: 'Şampuan sonrası saç uçlarına uygulayın, 2-3 dakika bekleyin ve durulayın.',
      price: 179.90,
      sku: 'SKM-MLS-001',
      stock: 65,
      images: '/images/sampuan-sacbakim/2.jpg',
      categoryId: createdCategories['sampuan-sac-bakim'].id,
    },
    {
      name: 'Tropikal Duş Jeli - 400 ml',
      slug: 'tropikal-dus-jeli-400ml',
      description: 'Ferahlatıcı tropikal kokusu ile günün enerjisi. Cildi temizler ve nemlendirir.',
      content: 'Doğal özler ve gliserin içerir. Cildi kurutmaz.',
      usage: 'Duş sırasında vücuda uygulayın, köpürtün ve durulayın.',
      price: 159.90,
      sku: 'DSJ-TRP-001',
      stock: 80,
      images: '/images/sampuan-sacbakim/3.jpg',
      categoryId: createdCategories['sampuan-sac-bakim'].id,
    },
    // Krem Bakım
    {
      name: 'Hyaluronic Acid Akgünlük Kremi - 50 ml',
      slug: 'hyaluronic-acid-akyildiz-kremi-50ml',
      description: 'Cildi derinlemesine nemlendiren hyaluronik asit içerikli gündüz kremi.',
      content: 'Yüksek molekül ağırlıklı hyaluronik asit, vitamin E ve panthenol içerir.',
      usage: 'Temiz cilde masaj yaparak uygulayın. Sabah kullanımı için idealdir.',
      price: 349.90,
      salePrice: 299.90,
      sku: 'KRM-HYA-001',
      stock: 40,
      images: '/images/krembakim/1.jpg',
      featured: true,
      categoryId: createdCategories['krem-bakim'].id,
    },
    {
      name: 'Collagen Peptit Nemlendirici Krem - 50 ml',
      slug: 'collagen-peptit-nemlendirici-krem-50ml',
      description: 'Cildi sıkılaştıran ve kırışıklıkları azaltan kolajen içerikli krem.',
      content: 'Hidrolize kolajen, peptit kompleksi ve shea butter ile formüle edilmiştir.',
      usage: 'Temiz cilde gece uygulanır. Hafif masaj yaparak emdirilir.',
      price: 379.90,
      sku: 'KRM-COL-001',
      stock: 35,
      images: '/images/krembakim/2.jpg',
      categoryId: createdCategories['krem-bakim'].id,
    },
    {
      name: 'Collagen Hyaluronic Acid Serum - 30 ml',
      slug: 'collagen-hyaluronic-acid-serum-30ml',
      description: 'Yoğun nemlendirici etki sağlayan kolajen ve hyaluronik asit serumu.',
      content: 'Kolajen, hyaluronik asit ve niacinamide içerir. Hızlı emilim.',
      usage: 'Temiz cilde 2-3 damla uygulayın, hafif masaj yapın. Sabah ve akşam kullanılabilir.',
      price: 299.90,
      salePrice: 259.90,
      sku: 'SRM-COL-001',
      stock: 50,
      images: '/images/krembakim/3.jpg',
      featured: true,
      categoryId: createdCategories['krem-bakim'].id,
    },
    {
      name: 'Peptit Complex Acid Krem - 50 ml',
      slug: 'peptit-complex-acid-krem-50ml',
      description: 'Anti-aging etkili peptit kompleksi içeren gece kremi.',
      content: 'Matrixyl 3000, argireline ve retinol alternatifleri içerir.',
      usage: 'Gece temiz cilde uygulayın. Göz çevresinden kaçının.',
      price: 399.90,
      sku: 'KRM-PEP-001',
      stock: 30,
      images: '/images/krembakim/4.jpg',
      categoryId: createdCategories['krem-bakim'].id,
    },
    // Bitkisel Yağlar (Difüzör)
    {
      name: 'Gül Yağı - 10 ml',
      slug: 'gul-yagi-10ml',
      description: 'Romantik ve rahatlat ıcı gül esansı. Difüzör ve aromaterapi için.',
      content: '%100 saf esans yağı. Sentetik katkı içermez.',
      usage: 'Difüzöre 3-5 damla ekleyin veya seyreltilmiş şekilde masaj yağı olarak kullanın.',
      price: 89.90,
      sku: 'YAG-GUL-001',
      stock: 120,
      images: '/images/bitkiselyaglar/1.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Biberiye Yağı - 10 ml',
      slug: 'biberiye-yagi-10ml',
      description: 'Zihin açıcı ve enerji verici biberiye esansı.',
      content: '%100 saf biberiye esans yağı. Terapötik kalite.',
      usage: 'Difüzöre 3-5 damla ekleyin. Konsantrasyonu artırır.',
      price: 79.90,
      sku: 'YAG-BBR-001',
      stock: 100,
      images: '/images/bitkiselyaglar/2.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Amber Oud Yağı - 10 ml',
      slug: 'amber-oud-yagi-10ml',
      description: 'Egzotik ve zengin amber oud kokusu. Lüks aromalar.',
      content: 'Amber ve oud karışımı premium esans yağı.',
      usage: 'Difüzöre 3-4 damla ekleyin. Ortama şık bir koku katar.',
      price: 129.90,
      sku: 'YAG-AMB-001',
      stock: 80,
      images: '/images/bitkiselyaglar/3.jpg',
      featured: true,
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Vanilya Yağı - 10 ml',
      slug: 'vanilya-yagi-10ml',
      description: 'Tatlı ve rahatlatıcı vanilya esansı.',
      content: 'Doğal vanilya özü ile üretilmiş esans yağı.',
      usage: 'Difüzöre 4-5 damla ekleyin.',
      price: 99.90,
      sku: 'YAG-VAN-001',
      stock: 90,
      images: '/images/bitkiselyaglar/4.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Sandal Ağacı Yağı - 10 ml',
      slug: 'sandal-agaci-yagi-10ml',
      description: 'Meditasyon ve rahatlama için sandal ağacı esansı.',
      content: '%100 saf sandal ağacı esans yağı.',
      usage: 'Difüzöre 3-4 damla ekleyin. Yoga ve meditasyon için ideal.',
      price: 119.90,
      sku: 'YAG-SND-001',
      stock: 70,
      images: '/images/bitkiselyaglar/5.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Okaliptus Nane Yağı - 10 ml',
      slug: 'okaliptus-nane-yagi-10ml',
      description: 'Ferahlatıcı ve solunum açıcı okaliptus nane karışımı.',
      content: 'Okaliptus ve nane esansı karışımı.',
      usage: 'Difüzöre 4-5 damla ekleyin. Soğuk algınlığında rahatlatır.',
      price: 89.90,
      sku: 'YAG-OKL-001',
      stock: 110,
      images: '/images/bitkiselyaglar/6.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Japon Kirazı Yağı - 10 ml',
      slug: 'japon-kirazi-yagi-10ml',
      description: 'Çiçeksi ve hafif japon kiraz çiçeği esansı.',
      content: 'Sakura (japon kirazı) esans yağı.',
      usage: 'Difüzöre 3-5 damla ekleyin.',
      price: 109.90,
      sku: 'YAG-KRZ-001',
      stock: 85,
      images: '/images/bitkiselyaglar/7.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Okyanus Yağı - 10 ml',
      slug: 'okyanus-yagi-10ml',
      description: 'Ferah okyanus esintisi. Deniz kokusu severlere özel.',
      content: 'Deniz ve okyanus notaları içeren esans karışımı.',
      usage: 'Difüzöre 4-5 damla ekleyin.',
      price: 94.90,
      sku: 'YAG-OKY-001',
      stock: 95,
      images: '/images/bitkiselyaglar/8.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Pudra Yağı - 10 ml',
      slug: 'pudra-yagi-10ml',
      description: 'Temiz ve pudra kokusu. Bebek pudrası notaları.',
      content: 'Pudra notaları içeren esans karışımı.',
      usage: 'Difüzöre 3-4 damla ekleyin.',
      price: 89.90,
      sku: 'YAG-PDR-001',
      stock: 100,
      images: '/images/bitkiselyaglar/9.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Afrika Yağı - 10 ml',
      slug: 'afrika-yagi-10ml',
      description: 'Egzotik ve sıcak Afrika esansları.',
      content: 'Afrika baharatları ve odunsu notalar.',
      usage: 'Difüzöre 3-4 damla ekleyin.',
      price: 99.90,
      sku: 'YAG-AFR-001',
      stock: 75,
      images: '/images/bitkiselyaglar/10.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    {
      name: 'Sedir Ağacı Yağı - 10 ml',
      slug: 'sedir-agaci-yagi-10ml',
      description: 'Odunsu ve yatıştırıcı sedir ağacı esansı.',
      content: '%100 saf sedir ağacı esans yağı.',
      usage: 'Difüzöre 3-4 damla ekleyin. Uyku kalitesini artırır.',
      price: 94.90,
      sku: 'YAG-SDR-001',
      stock: 80,
      images: '/images/bitkiselyaglar/11.jpg',
      categoryId: createdCategories['bitkisel-yaglar'].id,
    },
    // Oda ve Tekstil Kokuları
    {
      name: 'Powder Pudra Kokusu - 500 ml',
      slug: 'powder-pudra-kokusu-500ml',
      description: 'Temiz ve ferah pudra kokusu. Ev tekstilleri için ideal.',
      content: 'Uzun süre kalıcı formül. Leke yapmaz.',
      usage: 'Tekstillere 20-30 cm uzaktan sıkın. Odaya da kullanılabilir.',
      price: 129.90,
      salePrice: 109.90,
      sku: 'ODA-PDR-001',
      stock: 60,
      images: '/images/odavetekstil/1.jpg',
      categoryId: createdCategories['oda-tekstil-kokulari'].id,
    },
    {
      name: 'Delya Kokusu - 500 ml',
      slug: 'delya-kokusu-500ml',
      description: 'Zarif ve feminen Delya kokusu. Tüm mekanlara uygun.',
      content: 'Çiçeksi ve meyvemsi notalar. Kalıcı formül.',
      usage: 'Havaya, tekstillere ve perdelerevaya 20-30 cm mesafeden sıkın.',
      price: 129.90,
      sku: 'ODA-DEL-001',
      stock: 70,
      images: '/images/odavetekstil/2.jpg',
      featured: true,
      categoryId: createdCategories['oda-tekstil-kokulari'].id,
    },
    {
      name: 'Oud Kokusu - 500 ml',
      slug: 'oud-kokusu-500ml',
      description: 'Lüks ve etkileyici Oud kokusu. Oriental notalar.',
      content: 'Oud ve baharat notaları. Premium kalite.',
      usage: 'Oturma odası ve yatak odası için idealdir. 20-30 cm uzaktan sıkın.',
      price: 149.90,
      sku: 'ODA-OUD-001',
      stock: 50,
      images: '/images/odavetekstil/3.jpg',
      featured: true,
      categoryId: createdCategories['oda-tekstil-kokulari'].id,
    },
    {
      name: 'Amber Kokusu - 500 ml',
      slug: 'amber-kokusu-500ml',
      description: 'Sıcak ve sarıcı amber kokusu.',
      content: 'Amber ve vanilya notaları. Kalıcı etki.',
      usage: 'Ev tekstillerine ve odaya 20-30 cm mesafeden uygulayın.',
      price: 139.90,
      sku: 'ODA-AMB-001',
      stock: 55,
      images: '/images/odavetekstil/4.jpg',
      categoryId: createdCategories['oda-tekstil-kokulari'].id,
    },
    {
      name: 'Mavi Papatya Kokusu - 500 ml',
      slug: 'mavi-papatya-kokusu-500ml',
      description: 'Ferah ve temiz mavi papatya kokusu.',
      content: 'Papatya ve lavanta notaları. Rahatlatıcı etki.',
      usage: 'Yatak odası ve banyoda kullanım için ideal. 20-30 cm uzaktan sıkın.',
      price: 124.90,
      sku: 'ODA-PPT-001',
      stock: 65,
      images: '/images/odavetekstil/5.jpg',
      categoryId: createdCategories['oda-tekstil-kokulari'].id,
    },
  ]

  for (const prod of products) {
    const product = await prisma.product.upsert({
      where: { slug: prod.slug },
      update: {},
      create: prod,
    })
    console.log(`✅ Ürün oluşturuldu: ${product.name}`)
  }

  // Ayarları oluştur
  const settings = [
    {
      key: 'shipping_fee',
      value: '89.90',
      label: 'Kargo Ücreti (TL)',
      type: 'number',
    },
    {
      key: 'contact_phone',
      value: '+90 530 208 47 47',
      label: 'Telefon Numarası',
      type: 'text',
    },
    {
      key: 'contact_email',
      value: 'info@lioradg.com.tr',
      label: 'Email Adresi',
      type: 'email',
    },
    {
      key: 'contact_address',
      value: 'İstanbul, Türkiye',
      label: 'Adres',
      type: 'text',
    },
  ]

  for (const setting of settings) {
    await prisma.setting.upsert({
      where: { key: setting.key },
      update: {},
      create: setting,
    })
    console.log(`✅ Ayar oluşturuldu: ${setting.label} = ${setting.value}`)
  }

  console.log('🎉 Seeding tamamlandı!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

